<div>
    <section class="border-b border-[#e2e8f0] bg-white"><div class="mx-auto flex max-w-7xl items-center gap-5 px-4 py-10 sm:px-6 lg:px-8"><span class="grid h-14 w-14 place-items-center rounded-xl bg-[rgba(45,106,79,0.08)] text-[#2d6a4f]"><svg class="h-7 w-7" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 21V9M12 14c-5 0-8-3-8-8 5 0 8 3 8 8zm0 3c5 0 8-3 8-8-5 0-8 3-8 8z"/></svg></span><div><nav class="text-xs font-medium text-slate-500"><a href="{{ route('public.home') }}">Beranda</a><span class="mx-2">/</span><span class="text-[#2d6a4f]">Smart Agriculture</span></nav><h1 class="mt-2 text-2xl font-extrabold sm:text-3xl">Pertanian Presisi Desa Kalimati</h1></div></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Kondisi Pertanian 2026</h2></div><p class="mt-4 max-w-3xl text-sm leading-7 text-slate-600">Sawah 100% tadah hujan dan bergantung pada musim, dengan luas lahan pertanian 97,38 Ha.</p><div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach ($farmingConditions as $condition)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ $condition['label'] }}</p><p class="mt-3 text-3xl font-extrabold text-[#2d6a4f]">{{ $condition['value'] }} <span class="text-sm font-semibold">{{ $condition['unit'] }}</span></p><p class="mt-4 text-xs font-bold text-slate-500">{{ $condition['status'] }}</p></article>@endforeach</div></div></section>

    <section class="bg-[#0f172a] py-16 text-white"><div class="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[0.85fr_1.15fr] lg:px-8"><div><span class="rounded-full bg-[rgba(45,106,79,0.35)] px-3 py-1.5 text-xs font-bold text-emerald-200">{{ $aiNeed['model'] }}</span><h2 class="mt-5 text-3xl font-extrabold">Telemetri IoT & Analisis AI Gemini</h2><p class="mt-4 text-sm leading-7 text-slate-300">Teknologi diposisikan sebagai kebutuhan penguatan pertanian tadah hujan, bukan sebagai data sensor aktif yang belum terverifikasi.</p></div><article class="rounded-xl border border-white/10 bg-white/[0.06] p-6"><p class="text-sm leading-7 text-slate-200">{{ $aiNeed['summary'] }}</p><ul class="mt-6 grid gap-3 sm:grid-cols-2">@foreach ($aiNeed['priorities'] as $priority)<li class="flex gap-3 text-sm text-slate-300"><span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#2d6a4f]"></span><span>{{ $priority }}</span></li>@endforeach</ul></article></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Kelompok Tani Desa Kalimati</h2></div><div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach ($farmerGroups as $index => $group)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6 transition hover:-translate-y-1 hover:border-[#2d6a4f] hover:shadow-lg"><div class="flex items-start justify-between gap-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-[rgba(45,106,79,0.08)] font-extrabold text-[#2d6a4f]">{{ $index + 1 }}</span><span class="rounded-full bg-[#f1f5f9] px-3 py-1 text-xs font-bold text-slate-600">{{ $group['members'] }}</span></div><h3 class="mt-5 text-lg font-extrabold">{{ $group['name'] }}</h3><p class="mt-2 text-sm font-semibold text-[#2d6a4f]">{{ $group['hamlet'] }}</p></article>@endforeach</div></div></section>

    <section class="bg-[#f1f5f9] py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><article class="flex flex-col justify-between gap-6 rounded-xl border border-[#e2e8f0] bg-white p-7 sm:flex-row sm:items-center"><div><p class="text-xs font-bold uppercase tracking-wide text-[#2d6a4f]">P3A / Pamsimas</p><h2 class="mt-2 text-2xl font-extrabold">{{ $waterUserAssociation['name'] }}</h2><p class="mt-2 text-sm text-slate-500">{{ $waterUserAssociation['hamlet'] }}</p></div><div class="rounded-xl bg-[rgba(45,106,79,0.08)] px-5 py-4 text-center"><p class="text-2xl font-extrabold text-[#2d6a4f]">{{ $waterUserAssociation['members'] }}</p><p class="text-xs font-bold text-slate-500">{{ $waterUserAssociation['members'] }} anggota</p></div></article></div></section>

    <section class="pb-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex flex-col justify-between gap-5 rounded-xl bg-[rgba(45,106,79,0.08)] p-7 sm:flex-row sm:items-center"><div><h2 class="text-xl font-extrabold">Rencanakan pemantauan lahan secara spasial</h2><p class="mt-2 text-sm text-slate-600">Buka petak lahan dan titik pendukung pertanian pada peta interaktif desa.</p></div><a href="{{ route('public.gis.map') }}" class="w-fit rounded-full bg-[#2d6a4f] px-5 py-3 text-sm font-bold text-white hover:bg-[#1b4332]">Buka Peta Spasial -&gt;</a></div></div></section>
</div>