<div>
    <section class="border-b border-[#e2e8f0] bg-white"><div class="mx-auto flex max-w-7xl items-center gap-5 px-4 py-10 sm:px-6 lg:px-8"><span class="grid h-14 w-14 place-items-center rounded-xl bg-[rgba(45,106,79,0.08)] text-[#2d6a4f]"><svg class="h-7 w-7" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 21V9M12 14c-5 0-8-3-8-8 5 0 8 3 8 8zm0 3c5 0 8-3 8-8-5 0-8 3-8 8z"/></svg></span><div><nav class="text-xs font-medium text-slate-500"><a href="{{ route('public.home') }}">Beranda</a><span class="mx-2">/</span><span class="text-[#2d6a4f]">Smart Agriculture</span></nav><h1 class="mt-2 text-2xl font-extrabold sm:text-3xl">Pertanian Presisi Desa Kalimati</h1></div></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Lahan & Kelembagaan 2026</h2></div><div class="mt-8 grid gap-5 md:grid-cols-3">@foreach ($highlights as $item)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6"><p class="text-xs font-bold uppercase text-slate-500">{{ $item['title'] }}</p><p class="mt-3 text-2xl font-extrabold text-[#2d6a4f]">{{ $item['value'] }}</p><p class="mt-3 text-sm text-slate-500">{{ $item['detail'] }}</p></article>@endforeach</div></div></section>

    <section class="bg-[#f1f5f9] py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 class="text-2xl font-extrabold">Komoditas Unggulan & Pola Tanam</h2><div class="mt-8 grid gap-5 md:grid-cols-3">@foreach ($cropPatterns as $crop)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6"><p class="text-xs font-bold text-[#2d6a4f]">{{ $crop['label'] }}</p><h3 class="mt-3 text-xl font-extrabold">{{ $crop['value'] }}</h3><p class="mt-3 text-sm text-slate-500">{{ $crop['detail'] }}</p></article>@endforeach</div><div class="mt-12 grid gap-5 md:grid-cols-3">@foreach ($cultivationStages as $stage)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6"><h3 class="font-extrabold text-[#2d6a4f]">{{ $stage['title'] }}</h3><p class="mt-3 text-sm leading-6 text-slate-500">{{ $stage['description'] }}</p></article>@endforeach</div></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 class="text-2xl font-extrabold">Katalog Hama Lokal</h2><div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach ($pests as $pest)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6"><h3 class="font-extrabold">{{ $pest['name'] }}</h3><p class="mt-3 text-sm leading-6 text-slate-500">{{ $pest['impact'] }}</p></article>@endforeach</div></div></section>

    <section class="bg-[#0f172a] py-16 text-white"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 class="text-3xl font-extrabold">Telemetri Sensor IoT Tanah & AI Gemini</h2><div class="mt-8 grid gap-4 md:grid-cols-3">@foreach ($sensorModules as $sensor)<article class="rounded-xl border border-white/10 bg-white/[0.06] p-5"><p class="font-extrabold text-emerald-300">{{ $sensor['name'] }} ({{ $sensor['unit'] }})</p><p class="mt-2 text-sm text-slate-300">{{ $sensor['purpose'] }}</p></article>@endforeach</div><p class="mt-8 max-w-3xl text-sm leading-7 text-slate-300">{{ $aiNeed['summary'] }}</p><a href="{{ route('public.gis.map') }}" class="mt-6 inline-flex rounded-full bg-[#2d6a4f] px-5 py-3 text-sm font-bold">Buka Peta Spasial →</a></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 class="text-2xl font-extrabold">Gapoktan & Kelompok Tani</h2><p class="mt-3 max-w-3xl text-sm text-slate-500">Gapoktan menjadi wadah koordinasi, penyaluran pupuk subsidi, dan informasi bagi 720 petani.</p><div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach ($farmerGroups as $group)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6"><h3 class="font-extrabold">{{ str_replace('Poktan ', '', $group['name']) }}</h3><p class="mt-2 text-sm font-bold text-[#2d6a4f]">{{ $group['members'] }}</p></article>@endforeach</div></div></section>

    <section class="bg-[#f1f5f9] py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><article class="flex flex-col justify-between gap-6 rounded-xl border border-[#e2e8f0] bg-white p-7 sm:flex-row sm:items-center"><div><p class="text-xs font-bold uppercase tracking-wide text-[#2d6a4f]">P3A / Pamsimas</p><h2 class="mt-2 text-2xl font-extrabold">{{ $waterUserAssociation['name'] }}</h2><p class="mt-2 text-sm text-slate-500">{{ $waterUserAssociation['hamlet'] }}</p></div><div class="rounded-xl bg-[rgba(45,106,79,0.08)] px-5 py-4 text-center"><p class="text-2xl font-extrabold text-[#2d6a4f]">{{ $waterUserAssociation['members'] }}</p><p class="text-xs font-bold text-slate-500">{{ $waterUserAssociation['members'] }} anggota</p></div></article></div></section>

    <section class="pb-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex flex-col justify-between gap-5 rounded-xl bg-[rgba(45,106,79,0.08)] p-7 sm:flex-row sm:items-center"><div><h2 class="text-xl font-extrabold">Rencanakan pemantauan lahan secara spasial</h2><p class="mt-2 text-sm text-slate-600">Buka petak lahan dan titik pendukung pertanian pada peta interaktif desa.</p></div><a href="{{ route('public.gis.map') }}" class="w-fit rounded-full bg-[#2d6a4f] px-5 py-3 text-sm font-bold text-white hover:bg-[#1b4332]">Buka Peta Spasial -&gt;</a></div></div></section>
</div>