<div>
    <section class="relative h-[340px] overflow-hidden bg-[#0f172a] lg:h-[440px]">
        @foreach ($heroSlides as $index => $slide)
            <img wire:key="hero-{{ $index }}" src="{{ $slide['image'] }}" alt="Potensi Desa Kalimati" class="absolute inset-0 h-full w-full object-cover transition-opacity duration-500 {{ $activeHeroSlide === $index ? 'opacity-100' : 'opacity-0' }}">
        @endforeach
        <div class="absolute inset-0 bg-gradient-to-r from-[#0f172a]/95 via-[#0f172a]/80 to-transparent"></div>
        <div class="relative mx-auto flex h-full max-w-7xl items-center px-4 sm:px-6 lg:px-8"><div class="max-w-3xl text-white"><span class="rounded-full bg-[rgba(45,106,79,0.35)] px-4 py-2 text-xs font-bold text-emerald-100">{{ $heroSlides[$activeHeroSlide]['eyebrow'] }}</span><h1 class="mt-5 text-3xl font-extrabold sm:text-5xl">Portal Resmi Pemerintah Desa Kalimati</h1><p class="mt-4 max-w-2xl text-sm leading-7 text-slate-200 sm:text-lg">Mewujudkan Desa Digital, Mandiri, dan Pertanian Presisi Berkelanjutan.</p><p class="mt-3 text-sm font-medium text-emerald-100">{{ $headman['location'] }}</p><div class="mt-7 flex gap-3"><a href="{{ route('public.profile') }}" class="rounded-full bg-[#2d6a4f] px-5 py-3 text-sm font-bold hover:bg-[#1b4332]">Jelajahi Desa</a><a href="{{ route('public.gis.map') }}" class="rounded-full border border-white px-5 py-3 text-sm font-bold">Buka Peta</a></div></div></div>
        <div class="absolute bottom-5 left-1/2 flex -translate-x-1/2 gap-2">@foreach ($heroSlides as $index => $slide)<button type="button" wire:click="selectHeroSlide({{ $index }})" aria-label="Slide {{ $index + 1 }}" class="h-2.5 rounded-full {{ $activeHeroSlide === $index ? 'w-8 bg-white' : 'w-2.5 bg-white/50' }}"></button>@endforeach</div>
    </section>

    <section class="border-b border-[#e2e8f0] bg-[#f1f5f9]"><div class="mx-auto grid max-w-7xl gap-px bg-[#e2e8f0] sm:grid-cols-2 lg:grid-cols-4">@foreach ($stats as $stat)<article class="bg-[#f1f5f9] px-6 py-7"><p class="text-xs font-bold uppercase text-slate-500">{{ $stat['label'] }}</p><p class="mt-2 text-3xl font-extrabold text-[#2d6a4f]">{{ $stat['value'] }}</p><p class="mt-1 text-xs text-slate-500">{{ $stat['caption'] }}</p></article>@endforeach</div></section>

    <section class="py-16"><div class="mx-auto grid max-w-7xl gap-6 px-4 sm:px-6 lg:grid-cols-[240px_1fr] lg:px-8"><img src="{{ $headman['photo'] }}" alt="{{ $headman['name'] }}" class="h-64 w-full rounded-xl object-cover"><article class="rounded-xl border border-[#e2e8f0] bg-white p-7"><p class="text-xs font-bold uppercase text-[#2d6a4f]">Sambutan Kepala Desa</p><p class="mt-4 text-lg leading-8 text-slate-600">“{{ $headman['message'] }}”</p><p class="mt-6 font-extrabold">{{ $headman['name'] }}</p><p class="text-sm text-[#2d6a4f]">{{ $headman['position'] }} • {{ $headman['term'] }}</p></article></div></section>

    <section class="bg-[#f1f5f9] py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Akses Cepat</h2></div><div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach ($quickLinks as $index => $link)<a href="{{ $link['url'] }}" class="group rounded-xl border border-[#e2e8f0] bg-white p-6 transition hover:-translate-y-1 hover:border-[#2d6a4f]"><span class="grid h-10 w-10 place-items-center rounded-xl bg-[rgba(45,106,79,0.08)] font-extrabold text-[#2d6a4f]">{{ $index + 1 }}</span><h3 class="mt-5 font-extrabold">{{ $link['title'] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $link['description'] }}</p></a>@endforeach</div></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Berita & Pengumuman Terbaru</h2></div><div class="mt-8 grid gap-6 md:grid-cols-3">@foreach ($newsItems as $item)<article class="overflow-hidden rounded-xl border border-[#e2e8f0] bg-white"><img src="{{ $item['image'] }}" alt="{{ $item['title'] }}" class="h-44 w-full object-cover"><div class="p-6"><span class="rounded-full bg-[rgba(45,106,79,0.08)] px-3 py-1 text-xs font-bold text-[#2d6a4f]">{{ $item['category'] }}</span><time class="ml-2 text-xs text-slate-500">{{ $item['date'] }}</time><h3 class="mt-4 font-extrabold">{{ $item['title'] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $item['excerpt'] }}</p></div></article>@endforeach</div></div></section>
</div>