<div>
    <section class="border-b border-[#e2e8f0] bg-white"><div class="mx-auto flex max-w-7xl items-center gap-5 px-4 py-10 sm:px-6 lg:px-8"><span class="grid h-14 w-14 place-items-center rounded-xl bg-[rgba(45,106,79,0.08)] text-[#2d6a4f]"><svg class="h-7 w-7" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M3 21h18M5 21V8l7-5 7 5v13M9 21v-7h6v7"/></svg></span><div><nav class="text-xs font-medium text-slate-500"><a href="{{ route('public.home') }}">Beranda</a><span class="mx-2">/</span><span class="text-[#2d6a4f]">Profil & Sejarah</span></nav><h1 class="mt-2 text-2xl font-extrabold sm:text-3xl">Profil & Sejarah Desa Kalimati</h1></div></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">{{ $history['title'] }}</h2></div><article class="mt-8 rounded-xl border border-[#e2e8f0] bg-white p-6 shadow-sm sm:p-8">@foreach ($history['paragraphs'] as $paragraph)<p class="mt-3 text-sm leading-7 text-slate-600 first:mt-0">{{ $paragraph }}</p>@endforeach</article></div></section>

    <section class="bg-[#f1f5f9] py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Silsilah Kepala Desa</h2></div><div class="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">@foreach ($leaders as $index => $leader)<article class="rounded-xl border border-[#e2e8f0] bg-white p-5 transition hover:-translate-y-1 hover:border-[#2d6a4f]"><span class="grid h-9 w-9 place-items-center rounded-full bg-[#2d6a4f] text-sm font-bold text-white">{{ $index + 1 }}</span><p class="mt-4 text-xs font-bold uppercase text-[#2d6a4f]">{{ $leader['period'] }}</p><h3 class="mt-2 font-extrabold">{{ $leader['name'] }}</h3><p class="mt-2 text-xs leading-5 text-slate-500">{{ $leader['legacy'] }}</p></article>@endforeach</div></div></section>

    <section class="py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Pembagian Wilayah Dusun & Dukuh</h2></div><div class="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">@foreach ($hamlets as $hamlet)<article class="rounded-xl border border-[#e2e8f0] bg-white p-6 transition hover:-translate-y-1 hover:border-[#2d6a4f] hover:shadow-lg"><h3 class="text-lg font-extrabold">{{ $hamlet['name'] }}</h3><p class="mt-2 text-xs font-semibold text-[#2d6a4f]">{{ $hamlet['coverage'] }}</p><dl class="mt-5 grid gap-3 text-sm"><div class="flex justify-between border-b border-slate-100 pb-2"><dt class="text-slate-500">Wilayah</dt><dd class="font-bold">{{ $hamlet['rw'] }} • {{ $hamlet['rt'] }}</dd></div><div class="flex justify-between border-b border-slate-100 pb-2"><dt class="text-slate-500">Penduduk</dt><dd class="font-bold">{{ $hamlet['population'] }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Kepala Keluarga</dt><dd class="font-bold">{{ $hamlet['households'] }}</dd></div></dl></article>@endforeach</div></div></section>

    <section class="bg-[#f1f5f9] py-16"><div class="mx-auto grid max-w-7xl gap-6 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><article class="rounded-xl border border-[#e2e8f0] bg-white p-7"><p class="text-xs font-bold uppercase tracking-wide text-[#2d6a4f]">Visi Desa</p><h2 class="mt-3 text-xl font-extrabold">Arah Pembangunan Kalimati</h2><p class="mt-4 text-sm leading-7 text-slate-600">{{ $direction['vision'] }}</p></article><article class="rounded-xl border border-[#e2e8f0] bg-white p-7"><p class="text-xs font-bold uppercase tracking-wide text-[#2d6a4f]">Badan Usaha Milik Desa</p><h2 class="mt-3 text-xl font-extrabold">BUMDes {{ $villageEnterprise['name'] }}</h2><dl class="mt-6 grid gap-3 text-sm"><div class="flex justify-between border-b border-slate-100 pb-3"><dt class="text-slate-500">Ketua</dt><dd class="font-bold">{{ $villageEnterprise['chair'] }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Unit Usaha</dt><dd class="font-bold text-[#2d6a4f]">{{ $villageEnterprise['unit'] }}</dd></div></dl></article></div></section>

    <section class="py-16"><div class="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Kesenian Lokal</h2></div><div class="mt-8 grid gap-3 sm:grid-cols-2">@foreach ($culturalArts as $art)<div class="rounded-xl border border-[#e2e8f0] bg-white px-4 py-4 text-sm font-bold">{{ $art }}</div>@endforeach</div></div><div><div class="flex items-center gap-4"><span class="h-7 w-[5px] rounded-full bg-[#2d6a4f]"></span><h2 class="text-2xl font-extrabold">Keberagaman Tempat Ibadah</h2></div><div class="mt-8 grid gap-3">@foreach ($worshipPlaces as $place)<article class="rounded-xl border border-[#e2e8f0] bg-white p-5"><div class="flex items-center justify-between"><h3 class="font-extrabold">{{ $place['type'] }}</h3><span class="rounded-full bg-[rgba(45,106,79,0.08)] px-3 py-1 text-sm font-extrabold text-[#2d6a4f]">{{ $place['count'] }}</span></div><p class="mt-2 text-sm leading-6 text-slate-500">{{ $place['detail'] }}</p></article>@endforeach</div></div></div></section>
</div>